import {StyleSheet} from 'react-native';

export const FirstStep = StyleSheet.create({
  containerApp: {
    flex: 1,
    height: '100%',
    backgroundColor: '#384DFE',
  },
  imageApp: {
    position: 'absolute',
    width: 500,
    height: 250,
    left: -60,
    top: 127,
  },
  title: {
    position: 'absolute',
    width: 219,
    height: 33,
    top: 400,
    left: 75,
    fontSize: 24,
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: 'Poppins-Regular',
    color: '#fff',
  },
  paragraph: {
    position: 'absolute',
    width: 298,
    height: 44,
    left: 39,
    top: 450,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    color: '#ffffff',
  },
  button: {
    top: 520,
    left: 70,
    width: 223,
    height: 48,
    justifyContent: 'center',
    backgroundColor: '#FF685C',
    borderRadius: 6,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 22,
    color: '#ffffff',
    textAlign: 'center',
  },
});
